### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/infografia-de-las-librerias-uzias10#2]
[Infografía Librerias.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-uzias10/files/6340982/Infografia.Librerias.pdf)

**Comment by Anthony4523** [comment]
Calificación: 18

Calificó: Antonio González

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
